### ISSUE TITLE
Easier integration with redux-saga

### ISSUE THREAD

**Issue by doniyor2109** [doniyor2109/redux-lightweight#2]
Great idea from NL1GHT3D user

Little (possible) quality of life addition could be (what i've done for something similar):

```js
action.type = type
action.toString = () => type
```
then you can use the action itself as the index for a Map and also in sagas:
```js
let actionCreator = ....
```

```js
function *() {
  yield take(actionCreator.type, ....)
}
```

can then become:

```js
function *() {
  yield take(actionCreator, ...)
}
```
it's a small trick which works with objects where the function can then serve as an index:

```js
{
  [actionCreator]: ....
}
```
redux-saga has specific support for it: https://github.com/redux-saga/redux-saga/blob/d6bb78d96194b140c67083439848550f1119d910/packages/core/src/internal/matcher.js#L16

**Comment by nkovacic** [comment]
Will this work if minification is enabled?

**Comment by doniyor2109** [comment]
@nkovacic Yes it works
